set_property IOSTANDARD LVCMOS33 [get_ports LEDR]
set_property IOSTANDARD LVCMOS33 [get_ports LEDG]
set_property IOSTANDARD LVCMOS33 [get_ports LEDB]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports MB_IIC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports MB_IIC_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports TTY_txd]
set_property IOSTANDARD LVCMOS33 [get_ports TTY_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports PMIC_INT]
set_property IOSTANDARD LVCMOS33 [get_ports RTC_INT]
set_property IOSTANDARD LVCMOS33 [get_ports RTC_32K]
set_property IOSTANDARD LVCMOS33 [get_ports BT_txd]
set_property IOSTANDARD LVCMOS33 [get_ports BT_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports WL_EN]
set_property IOSTANDARD LVCMOS33 [get_ports PL_CLK]
set_property PACKAGE_PIN L20 [get_ports LEDR]
set_property PACKAGE_PIN M20 [get_ports LEDG]
set_property PACKAGE_PIN L19 [get_ports LEDB]
set_property PACKAGE_PIN M19 [get_ports LED2]
set_property PACKAGE_PIN Y14 [get_ports LED3]
set_property PACKAGE_PIN M14 [get_ports MB_IIC_scl_io]
set_property PACKAGE_PIN M15 [get_ports MB_IIC_sda_io]
set_property PACKAGE_PIN J19 [get_ports TTY_txd]
set_property PACKAGE_PIN K19 [get_ports TTY_rxd]
set_property PACKAGE_PIN M17 [get_ports PMIC_INT]
set_property PACKAGE_PIN L15 [get_ports RTC_INT]
set_property PACKAGE_PIN L16 [get_ports RTC_32K]
set_property PACKAGE_PIN K16 [get_ports BT_txd]
set_property PACKAGE_PIN J16 [get_ports BT_rxd]
set_property PACKAGE_PIN J14 [get_ports WL_EN]
set_property PACKAGE_PIN H16 [get_ports PL_CLK]
set_property OFFCHIP_TERM NONE [get_ports LEDB]
set_property OFFCHIP_TERM NONE [get_ports LEDG]
set_property OFFCHIP_TERM NONE [get_ports LEDR]
set_property OFFCHIP_TERM NONE [get_ports LED2]
set_property OFFCHIP_TERM NONE [get_ports LED3]
create_clock -period 20.000 -name pl_clk_in [get_ports PL_CLK]
#set_input_jitter pl_clk 0.6

set_property IOSTANDARD LVCMOS33 [get_ports OPT_IIC_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports OPT_IIC_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports OPT_INT]
set_property IOSTANDARD LVCMOS33 [get_ports AD_BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CTRL]
set_property IOSTANDARD LVCMOS33 [get_ports AD_FCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AD_SDATA]
set_property IOSTANDARD LVCMOS33 [get_ports BUZZ_N]
set_property IOSTANDARD LVCMOS33 [get_ports BUZZ_P]
set_property IOSTANDARD LVCMOS33 [get_ports VFD_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports VFD_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports VFD_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports VFD_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports VH_EN]
set_property IOSTANDARD LVCMOS33 [get_ports VF_EN]
set_property IOSTANDARD LVCMOS33 [get_ports VF_T1]
set_property IOSTANDARD LVCMOS33 [get_ports VF_T2]
set_property IOSTANDARD LVCMOS33 [get_ports BUT1]
set_property IOSTANDARD LVCMOS33 [get_ports BUT2]
set_property IOSTANDARD LVCMOS33 [get_ports BUT3]
set_property IOSTANDARD LVCMOS33 [get_ports BUT4]
set_property IOSTANDARD LVCMOS33 [get_ports VFD_INT]

set_property PACKAGE_PIN U20 [get_ports OPT_IIC_scl_io]
set_property PACKAGE_PIN Y17 [get_ports OPT_IIC_sda_io]
set_property PACKAGE_PIN W20 [get_ports OPT_INT]
set_property PACKAGE_PIN W18 [get_ports AD_BCLK]
set_property PACKAGE_PIN Y19 [get_ports AD_CTRL]
set_property PACKAGE_PIN Y18 [get_ports AD_FCLK]
set_property PACKAGE_PIN U18 [get_ports AD_SDATA]
set_property PACKAGE_PIN V15 [get_ports BUZZ_N]
set_property PACKAGE_PIN W15 [get_ports BUZZ_P]
set_property PACKAGE_PIN D20 [get_ports VFD_SCK]
set_property PACKAGE_PIN B19 [get_ports VFD_SDO]
set_property PACKAGE_PIN C20 [get_ports VFD_nCS]
set_property PACKAGE_PIN E18 [get_ports VFD_nRST]
set_property PACKAGE_PIN G19 [get_ports VH_EN]
set_property PACKAGE_PIN F19 [get_ports VF_EN]
set_property PACKAGE_PIN J20 [get_ports VF_T1]
set_property PACKAGE_PIN H20 [get_ports VF_T2]
set_property PACKAGE_PIN W13 [get_ports BUT1]
set_property PACKAGE_PIN V12 [get_ports BUT2]
set_property PACKAGE_PIN W16 [get_ports BUT3]
set_property PACKAGE_PIN V16 [get_ports BUT4]
set_property PACKAGE_PIN E19 [get_ports VFD_INT]

# set_property SLEW FAST [get_ports VFD_nCS]
# set_property SLEW FAST [get_ports VFD_nRST]
# set_property SLEW FAST [get_ports VFD_SCK]
# set_property SLEW FAST [get_ports VFD_SDO]
# set_property SLEW FAST [get_ports VF_T2]
# set_property SLEW FAST [get_ports VF_T1]
# set_property SLEW FAST [get_ports VH_EN]
# set_property SLEW FAST [get_ports VF_EN]
